export const mockedResponseSc = {
  'id': 155,
  'employee': {
    'createdDateTime': null,
    'modifiedDateTime': [2020, 4, 6, 12, 19, 8, 809000000],
    'id': 8000,
    'firstName': 'Michaela',
    'lastName': 'Mitarbeiterin',
    'login': 'test.pr.mitarbeiter1',
    'email': 'mocked.test.pr.mitarbeiter1@senacor.com',
    'supervisorId': 297,
    'officeLocation': 'Mocked office',
    'entryDate': [2019, 9, 30],
    'endDate': null,
    'department': '',
    'position': '',
    'ignoreScGeneration': false,
    'employeeStatus': 'ACTIVE',
    'roles': [{ 'id': 3, 'name': 'EMPLOYEE' }]
  },
  'supervisor': {
    'createdDateTime': [2020, 2, 24, 8, 37, 45, 967000000],
    'modifiedDateTime': [2020, 4, 9, 9, 56, 57, 694000000],
    'id': 297,
    'firstName': 'Katharina',
    'lastName': 'Landes',
    'login': 'klandes',
    'email': 'Katharina.Landes@senacor.com',
    'supervisorId': 8003,
    'officeLocation': 'Nürnberg',
    'entryDate': [2007, 9, 17],
    'endDate': null,
    'department': 'HR',
    'position': 'Partner',
    'ignoreScGeneration': true,
    'employeeStatus': 'ACTIVE',
    'roles': [{ 'id': 5, 'name': 'SUPERVISOR' }]
  },
  'reviewer1': {
    'createdDateTime': [2020, 2, 24, 8, 37, 45, 967000000],
    'modifiedDateTime': [2020, 4, 9, 9, 56, 57, 694000000],
    'id': 297,
    'firstName': 'Katharina',
    'lastName': 'Landes',
    'login': 'klandes',
    'email': 'Katharina.Landes@senacor.com',
    'supervisorId': 8003,
    'officeLocation': 'Nürnberg',
    'entryDate': [2007, 9, 17],
    'endDate': null,
    'department': 'HR',
    'position': 'Partner',
    'ignoreScGeneration': true,
    'employeeStatus': 'ACTIVE',
    'roles': [{ 'id': 5, 'name': 'SUPERVISOR' }]
  },
  'reviewer2': null,
  'department': '',
  'createdDate': [2020, 4, 6],
  'deadline': [2020, 7, 15],
  'classification': 'SENIOR_MANAGEMENT',
  'statusSet': ['SC_WITHOUT_PR_PRESET', 'REVIEWER_PUBLISHED', 'SC_WITHOUT_PR_CHOSEN', 'EMPLOYEE_PUBLISHED'],
  'periodName': '1. Halbjahr 2020',
  'finalMeetingDate': null,
  'privateReviewerData': null,
  'privateEmployeeData': {
    'dailyBusiness': [{ 'title': 'ccc', 'weight': 1.0, 'evaluation': 3, 'description': '', 'achievement': '', 'comment': '' }],
    'project': [{ 'title': 'ccc', 'weight': 1.0, 'evaluation': 3, 'description': '', 'achievement': '', 'comment': '' }],
    'workQuality': { 'title': null, 'weight': 0.0, 'evaluation': 3, 'description': '', 'achievement': '', 'comment': '' },
    'workEfficiency': { 'title': null, 'weight': 0.0, 'evaluation': 2, 'description': '', 'achievement': '', 'comment': '' },
    'skillsInTheFields': null,
    'impactOnTeam': null,
    'serviceQuality': null,
    'impactOnCompany': null,
    'skillsWeightPercentage': null
  },
  'publishedReviewerData': {
    'dailyBusiness': [{
      'title': 'ccc',
      'weight': 1.0,
      'evaluation': 0,
      'description': 'xxx',
      'achievement': 'xxx',
      'comment': ''
    }],
    'project': [{ 'title': 'ccc', 'weight': 1.0, 'evaluation': 0, 'description': '', 'achievement': '', 'comment': '' }],
    'workQuality': { 'title': null, 'weight': 0.0, 'evaluation': 0, 'description': '', 'achievement': '', 'comment': '' },
    'workEfficiency': { 'title': null, 'weight': 0.0, 'evaluation': 0, 'description': '', 'achievement': '', 'comment': '' },
    'skillsInTheFields': null,
    'impactOnTeam': null,
    'serviceQuality': null,
    'impactOnCompany': null,
    'skillsWeightPercentage': null
  },
  'publishedEmployeeData': {
    'dailyBusiness': [{
      'title': 'ccc',
      'weight': 1.0,
      'evaluation': 3,
      'description': '',
      'achievement': '',
      'comment': ''
    }],
    'project': [{ 'title': 'ccc', 'weight': 1.0, 'evaluation': 3, 'description': '', 'achievement': '', 'comment': '' }],
    'workQuality': { 'title': null, 'weight': 0.0, 'evaluation': 3, 'description': '', 'achievement': '', 'comment': '' },
    'workEfficiency': { 'title': null, 'weight': 0.0, 'evaluation': 2, 'description': '', 'achievement': '', 'comment': '' },
    'skillsInTheFields': null,
    'impactOnTeam': null,
    'serviceQuality': null,
    'impactOnCompany': null,
    'skillsWeightPercentage': null
  }
};
