export enum SC_STATUS {
  WITH_PR = 'SC_WITH_PR_CHOSEN',
  SC_WITH_PR_PRESET = 'SC_WITH_PR_PRESET',
  WITHOUT_PR = 'SC_WITHOUT_PR_CHOSEN',
  SC_WITHOUT_PR_PRESET = 'SC_WITHOUT_PR_PRESET',
  EMPLOYEE_PUBLISHED = 'EMPLOYEE_PUBLISHED',
  REVIEWER_PUBLISHED = 'REVIEWER_PUBLISHED',
  ARCHIVED = 'ARCHIVED',
  CLOSED = 'CLOSED'
}

export enum GENERAL_STATUS {
  INITIALIZATION = 'INITIALIZATION',
  IN_PROGRESS = 'IN_PROGRESS',
  READY_TO_CLOSE = 'READY_TO_CLOSE',
  DONE = 'DONE',
  ARCHIVED = 'ARCHIVED'
}

export enum USER_SC_RELATION {
  REVIEWER,
  OWNER,
  PERSONAL_DEVELOPMENT,
  SUPERVISOR,
  OTHER_SUPERVISOR,
  NONE
}
